"""Event-level variables (lepton, MET, multiplicities, ttH tagger inputs)."""
from .helpers import V, count_edges

VARIABLES = [
    # event kinematics
    V("ht", "ht", r"$H_{\mathrm{T}}$ [GeV]", xlim=(0.0, 1500.0)),
    V("ht_b", "ht_b", r"$H_{\mathrm{T}}$ (b jets) [GeV]", xlim=(0.0, 800.0)),
    V("ht_c", "ht_c", r"$H_{\mathrm{T}}$ (c jets) [GeV]", xlim=(0.0, 800.0)),
    V("ht_bc", "ht_bc", r"$H_{\mathrm{T}}$ (b+c jets) [GeV]", xlim=(0.0, 800.0)),
    V("met", "met", r"$p_{\mathrm{T}}^{\mathrm{miss}}$ [GeV]",
      xlim=(0.0, 300.0)),
    V("met_phi", "met_phi", r"$\phi(\vec{p}_{\mathrm{T}}^{\mathrm{miss}})$",
      xlim=(-3.2, 3.2)),
    V("PV_npvs", "PV_npvs", "Number of primary vertices", xlim=(0.0, 60.0)),
    # multiplicities
    V("n_ak4", "n_ak4", "Number of AK4 jets", edges=count_edges(14)),
    V("n_ak8", "n_ak8", "Number of AK8 jets", edges=count_edges(4)),
    V("n_btag", "n_btag", "Number of loose-b-tagged AK4 jets",
      edges=count_edges(7)),
    V("n_btagM", "n_btagM", "Number of medium-b-tagged AK4 jets",
      edges=count_edges(7)),
    V("n_btagT", "n_btagT", "Number of tight-b-tagged AK4 jets",
      edges=count_edges(7)),
    V("n_ctag", "n_ctag", "Number of loose-c-tagged AK4 jets",
      edges=count_edges(7)),
    V("n_ctagM", "n_ctagM", "Number of medium-c-tagged AK4 jets",
      edges=count_edges(7)),
    V("n_ctagT", "n_ctagT", "Number of tight-c-tagged AK4 jets",
      edges=count_edges(7)),
    # leptons
    V("lep1_pt", "lep1_pt", r"Leading lepton $p_{\mathrm{T}}$ [GeV]",
      xlim=(0.0, 300.0)),
    V("lep1_eta", "lep1_eta", r"Leading lepton $\eta$", xlim=(-2.5, 2.5)),
    V("lep1_phi", "lep1_phi", r"Leading lepton $\phi$", xlim=(-3.2, 3.2)),
    V("lep1_mass", "lep1_mass", "Leading lepton mass [GeV]",
      xlim=(0.0, 0.5)),
    V("lep1_etaSC", "lep1_etaSC", r"Leading lepton $\eta_{\mathrm{SC}}$",
      xlim=(-2.6, 2.6)),
    V("lep2_pt", "lep2_pt", r"Subleading lepton $p_{\mathrm{T}}$ [GeV]",
      xlim=(0.0, 200.0)),
    V("lep2_eta", "lep2_eta", r"Subleading lepton $\eta$",
      xlim=(-2.5, 2.5)),
    V("lep2_mass", "lep2_mass", "Subleading lepton mass [GeV]",
      xlim=(0.0, 1.0)),
    # ttH-tagger-style combination variables
    V("mass_minDR_b", "mass_minDR_b", r"$m_{b}$ (min $\Delta R$) [GeV]",
      xlim=(0.0, 400.0)),
    V("mass_minDR_bc", "mass_minDR_bc", r"$m_{bc}$ (min $\Delta R$) [GeV]",
      xlim=(0.0, 400.0)),
    V("mass_minDR_c", "mass_minDR_c", r"$m_{c}$ (min $\Delta R$) [GeV]",
      xlim=(0.0, 400.0)),
    V("maxMass_b", "maxMass_b", r"$\max m_{b}$ [GeV]", xlim=(0.0, 400.0)),
    V("maxMass_bc", "maxMass_bc", r"$\max m_{bc}$ [GeV]", xlim=(0.0, 400.0)),
    V("maxMass_c", "maxMass_c", r"$\max m_{c}$ [GeV]", xlim=(0.0, 400.0)),
    V("minDR_b", "minDR_b", r"min $\Delta R_{b}$", xlim=(0.0, 4.0)),
    V("minDR_bc", "minDR_bc", r"min $\Delta R_{bc}$", xlim=(0.0, 4.0)),
    V("minDR_c", "minDR_c", r"min $\Delta R_{c}$", xlim=(0.0, 4.0)),
    # reconstructed W-boson candidate
    V("v_pt", "v_pt", r"$V$ candidate $p_{\mathrm{T}}$ [GeV]",
      xlim=(0.0, 400.0)),
    V("v_eta", "v_eta", r"$V$ candidate $\eta$", xlim=(-2.5, 2.5)),
    V("v_phi", "v_phi", r"$V$ candidate $\phi$", xlim=(-3.2, 3.2)),
    V("v_mass", "v_mass", r"$V$ candidate mass [GeV]", xlim=(0.0, 300.0)),
]
